# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1199, 935)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 0, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.Ed_find = QtWidgets.QLineEdit(self.groupBox_4)
        self.Ed_find.setObjectName("Ed_find")
        self.gridLayout_4.addWidget(self.Ed_find, 0, 1, 1, 1)
        self.Ed_find2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.Ed_find2.setObjectName("Ed_find2")
        self.gridLayout_4.addWidget(self.Ed_find2, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout.addWidget(self.tableWidget)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_title = QtWidgets.QLabel(self.groupBox_3)
        self.label_title.setObjectName("label_title")
        self.gridLayout_3.addWidget(self.label_title, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 1, 0, 1, 1)
        self.label_pix = QtWidgets.QLabel(self.groupBox_3)
        self.label_pix.setObjectName("label_pix")
        self.gridLayout_3.addWidget(self.label_pix, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_id = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_id.setObjectName("spinBox_id")
        self.gridLayout_2.addWidget(self.spinBox_id, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        self.Ed_num = QtWidgets.QLineEdit(self.groupBox)
        self.Ed_num.setObjectName("Ed_num")
        self.gridLayout_2.addWidget(self.Ed_num, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.Ed_director = QtWidgets.QLineEdit(self.groupBox)
        self.Ed_director.setObjectName("Ed_director")
        self.gridLayout_2.addWidget(self.Ed_director, 2, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 4, 1, 1)
        self.spinBox_age = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_age.setMaximum(2100)
        self.spinBox_age.setObjectName("spinBox_age")
        self.gridLayout_2.addWidget(self.spinBox_age, 2, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 6, 1, 1)
        self.lineEdit_country = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_country.setObjectName("lineEdit_country")
        self.gridLayout_2.addWidget(self.lineEdit_country, 2, 7, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 7, 1, 1)
        self.Ed_tags = QtWidgets.QLineEdit(self.groupBox)
        self.Ed_tags.setObjectName("Ed_tags")
        self.gridLayout_2.addWidget(self.Ed_tags, 3, 8, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 5, 8, 1, 1)
        self.Ed_img = QtWidgets.QLineEdit(self.groupBox)
        self.Ed_img.setObjectName("Ed_img")
        self.gridLayout_2.addWidget(self.Ed_img, 5, 9, 1, 1)
        self.addBtn = QtWidgets.QPushButton(self.groupBox)
        self.addBtn.setObjectName("addBtn")
        self.gridLayout_2.addWidget(self.addBtn, 6, 0, 1, 2)
        self.Ed_prim = QtWidgets.QLineEdit(self.groupBox)
        self.Ed_prim.setObjectName("Ed_prim")
        self.gridLayout_2.addWidget(self.Ed_prim, 5, 2, 1, 4)
        self.Te_desc = QtWidgets.QTextEdit(self.groupBox)
        self.Te_desc.setObjectName("Te_desc")
        self.gridLayout_2.addWidget(self.Te_desc, 4, 2, 1, 8)
        self.Ed_actors = QtWidgets.QLineEdit(self.groupBox)
        self.Ed_actors.setObjectName("Ed_actors")
        self.gridLayout_2.addWidget(self.Ed_actors, 3, 2, 1, 3)
        self.Ed_name = QtWidgets.QLineEdit(self.groupBox)
        self.Ed_name.setText("")
        self.Ed_name.setObjectName("Ed_name")
        self.gridLayout_2.addWidget(self.Ed_name, 0, 5, 1, 5)
        self.Ed_title = QtWidgets.QLineEdit(self.groupBox)
        self.Ed_title.setObjectName("Ed_title")
        self.gridLayout_2.addWidget(self.Ed_title, 1, 5, 1, 5)
        self.horizontalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Фильтр"))
        self.label_15.setText(_translate("MainWindow", "Название:"))
        self.label_12.setText(_translate("MainWindow", "Жанр:"))
        self.label_14.setText(_translate("MainWindow", "Название оригинальное:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Подробно"))
        self.label_title.setText(_translate("MainWindow", "Название"))
        self.label_13.setText(_translate("MainWindow", "№"))
        self.label_pix.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Просмотр"))
        self.groupBox.setTitle(_translate("MainWindow", "Добавить новую запись в базу данных"))
        self.label.setText(_translate("MainWindow", "id:"))
        self.label_11.setText(_translate("MainWindow", "Номер:"))
        self.label_2.setText(_translate("MainWindow", "Название оригинальное:"))
        self.label_5.setText(_translate("MainWindow", "Жанр:"))
        self.label_6.setText(_translate("MainWindow", "Название в переводе:"))
        self.label_7.setText(_translate("MainWindow", "Режисер:"))
        self.label_3.setText(_translate("MainWindow", "Год:"))
        self.label_4.setText(_translate("MainWindow", "Страна:"))
        self.label_8.setText(_translate("MainWindow", "Актёры:"))
        self.label_16.setText(_translate("MainWindow", "Тэги:"))
        self.label_9.setText(_translate("MainWindow", "Описание:"))
        self.label_10.setText(_translate("MainWindow", "Примечание:"))
        self.label_17.setText(_translate("MainWindow", "Картинка:"))
        self.addBtn.setText(_translate("MainWindow", "Ok"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Добавить"))

